spring:
  datasource:
    username: test
    password: test
    url: jdbc:mysql://localhost:3306/db-test
    driver-class-name: com.mysql.cj.jdbc.Driver
#management:
#  metrics:
#    export:
#      influx:
#        db: '@spring.metric.db.name@'
#        uri: '@spring.metric.db.url@'