spring:
  datasource:
    username: '@spring.datasource.username@'
    password: '@spring.datasource.password@'
    url: '@spring.datasource.url@'
    driver-class-name: '@spring.datasource.driver-class-name@'
