spring:
  datasource:
    username: '@spring.datasource.username@'
    password: '@spring.datasource.password@'
    url: '@spring.datasource.url@'
    driver-class-name: '@spring.datasource.driver-class-name@'
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
  mail:
    host: '@mail.host@'
    port: '@mail.port@'
    password: '@mail.password@'
    username: '@mail.username@'
    test-connection: '@mail.test.connection@'
  rabbitmq:
    host: '@rabbitmq.host@'
    username: '@rabbitmq.username@'
    password: '@rabbitmq.password@'
    port: '@rabbitmq.port@'
management:
  metrics:
    export:
      influx:
        db: '@spring.metric.db.name@'
        uri: '@spring.metric.db.url@'
        user-name: '@spring.metric.db.username@'
        password: '@spring.metric.db.password@'
        enabled: '@spring.enable.metrict@'
  endpoints:
    web:
      exposure:
        include: "*"
    prometheus:
      enabled: true