management:
  metrics:
    export:
      influx:
        db: '@spring.metric.db.name@'
        uri: '@spring.metric.db.url@'
        user-name: '@spring.metric.db.username@'
        password:   '@spring.metric.db.password@'
        enabled: false