version: '3.3'
services:
  db-test:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: 'password'
        MYSQL_DATABASE: 'db-test'
        MYSQL_USER: 'test'
        MYSQL_PASSWORD: 'test'
#    command: [ 'mysqld','--init-file=/docker/database/install_db.sql','--log-bin-trust-function-creators=TRUE',"--explicit_defaults_for_timestamp", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
#    volumes:
#      - ./database:/docker/database
    ports:
      - '3306:3306'
    networks:
      - test
  db-liquibase:
    build:
      context: ../
      dockerfile: ./docker/db_liquibase/Dockerfile
      args:
        SCHEMA_JAR_DIR: ${SCHEMA_JAR_DIR}
        SCHEMA_JAR: ${SCHEMA_JAR}
    depends_on:
      - db-test
    container_name: db-liquibase
    environment:
      - LIQUIBASE_URL=jdbc:mysql://localhost:3306/db-test?verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true
      - LIQUIBASE_USERNAME=test
      - LIQUIBASE_PASSWORD=test
      - LIQUIBASE_DRIVER=com.mysql.cj.jdbc.Driver
      - LIQUIBASE_CLASSPATH=/mysql-connector-java-8.0.18.jar
      - LIQUIBASE_CHANGELOG=/liquibase/db-changelog-master.xml
    networks:
      - test
networks:
  test:
    external: true
