version: '3.3'
services:
    app:
      image: '22071996/multi-module-test:1'
      build:
        context: ../
        dockerfile: ./docker/app/Dockerfile
      container_name: app_test
      expose:
        - 8080
      ports:
        - 8080:8080
      environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://db-test:3306/test-db
        - SPRING_DATASOURCE_USERNAME=test
        - SPRING_DATASOURCE_PASSWORD=test
        - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
        - MANAGEMENT_METRICS_EXPORT_INFLUX_DB=http://influxdb:8086
        - MANAGEMENT_METRICS_EXPORT_INFLUX_URI=db0
        - MANAGEMENT_METRICS_EXPORT_INFLUX_USER-name=admin
        - MANAGEMENT_METRICS_EXPORT_INFLUX_PASSWORD=admin
      restart: unless-stopped
      depends_on:
        - db-test
      links:
        - db-test
      networks:
        - test
    db-test:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: 'password'
        MYSQL_DATABASE: 'test-db'
        MYSQL_USER: 'test'
        MYSQL_PASSWORD: 'test'
      ports:
        - '3306:3306'
      networks:
        - test
    db-liquibase:
      build:
        context: ../
        dockerfile: ./docker/db_liquibase/Dockerfile
        args:
          SCHEMA_JAR_DIR: ${SCHEMA_JAR_DIR}
          SCHEMA_JAR: ${SCHEMA_JAR}
      depends_on:
        - db-test
      container_name: db-liquibase
      environment:
        - LIQUIBASE_URL=jdbc:mysql://db-test:3306/test-db
        - LIQUIBASE_USERNAME=test
        - LIQUIBASE_PASSWORD=test
        - LIQUIBASE_DRIVER=com.mysql.cj.jdbc.Driver
        - LIQUIBASE_CLASSPATH=/mysql-connector-java-8.0.18.jar
        - LIQUIBASE_CHANGELOG=/liquibase/changelog-master.xml
      networks:
        - test
    grafana:
      image: grafana/grafana:latest
      ports:
        - '3000:3000'
      depends_on:
        - influxdb
      environment:
        - GF_SECURITY_ADMIN_USER=grafana
        - GF_SECURITY_ADMIN_PASSWORD=grafana
      volumes:
        - grafana-storage:/var/lib/influxdb
        - ./grafana/:/etc/grafana/provisioning

      networks:
        - test
    influxdb:
      container_name: influxdb
      image: influxdb:1.7.10-alpine
      ports:
        - '8086:8086'
      volumes:
        - influxdb-storage:/var/lib/influxdb
      networks:
        - test
      environment:
        - INFLUXDB_DB=db0
        - INFLUXDB_ADMIN_USER=adminn
        - INFLUXDB_ADMIN_PASSWORD=adminn
networks:
  test:
    external: true

volumes:
  influxdb-storage:
  grafana-storage: