{
 "title": "test-app-prometheuss",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "test_counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "test_counter_app_total" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count"
    }
   ]
  },
  {
   "title": "test_timer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "test_timer_app_seconds_count" },
    { "expr": "test_timer_app_seconds_max" },
    { "expr": "test_timer_app_seconds_sum" }
   ]
  },
  {
   "title": "jvm",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_buffer_memory_used_bytes" }
   ]
  }
 ]
}