version: '3.3'
services:

        nginx:
          restart: always
          build:
            context: .
            dockerfile: nginx.dockerfile
          expose:
            - "80"
          ports:
            - "80:80"
          depends_on:
            - messaging-service
            - notifications-service
          networks:
            - app-network
#    app:
#      build:
#        context: ../
#        dockerfile: ./docker-separate-module/app/Dockerfile
#      network_mode: bridge
#      container_name: app_test
#      expose:
#        - 8080
#      ports:
#        - 8080:8080
#      environment:
#        - SPRING_DATASOURCE_URL=jdbc:mysql://db-test:3306/db-test
#        - SPRING_DATASOURCE_USERNAME=test
#        - SPRING_DATASOURCE_PASSWORD=test
#      restart: unless-stopped
#      depends_on:
#        - db-test
#    db-test:
#      image: mysql:5.7
#      restart: always
#      environment:
#        MYSQL_ROOT_PASSWORD: 'password'
#        MYSQL_DATABASE: 'db-test'
#        MYSQL_USER: 'test'
#        MYSQL_PASSWORD: 'test'
#      #    command: [ 'mysqld','--init-file=/docker/database/install_db.sql','--log-bin-trust-function-creators=TRUE',"--explicit_defaults_for_timestamp", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
#      #    volumes:
#      #      - ./database:/docker/database
#      ports:
#        - '3306:3306'
#      networks:
#        - test
#    db-liquibase:
#      build:
#        context: ../
#        dockerfile: ./docker/db_liquibase/Dockerfile
#        args:
#          SCHEMA_JAR_DIR: ${SCHEMA_JAR_DIR}
#          SCHEMA_JAR: ${SCHEMA_JAR}
#      depends_on:
#        - db-test
#      container_name: db-liquibase
#      environment:
#        - LIQUIBASE_URL=jdbc:mysql://db-test:3306/db-test
#        - LIQUIBASE_USERNAME=test
#        - LIQUIBASE_PASSWORD=test
#        - LIQUIBASE_DRIVER=com.mysql.cj.jdbc.Driver
#        - LIQUIBASE_CLASSPATH=/mysql-connector-java-8.0.18.jar
#        - LIQUIBASE_CHANGELOG=/liquibase/changelog-master.xml
#      networks:
#        - test
networks:
  test:
    external: true
